config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :booster_sets, only: [:index] do
    resources :booster_packs, only: [:index, :show]
  end
  resources :cards, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booster_pack.rb
class BoosterPack < ApplicationRecord
  belongs_to :booster_set
  belongs_to :card
end

app/models/booster_set.rb
class BoosterSet < ApplicationRecord
  has_many :booster_packs
  has_many :cards, through: :booster_packs
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :booster_packs
  has_many :booster_sets, through: :booster_packs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/booster_packs_controller.rb
class BoosterPacksController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    find_booster_packs
  end

  def show
    find_booster_packs
    @commons = @booster_packs.select{|rarity| rarity.card_rarity == "Common" || rarity.card_rarity == "Short Print" || rarity.card_rarity == "Super Short Print"}
    @rares = @booster_packs.select{|rarity| rarity.card_rarity == "Rare"}
    @extra = @booster_packs.reject{|rarity| rarity.card_rarity == "Rare"}
    @pack = []
    7.times do
      @pack << @commons.sample
    end
    @pack << @rares.sample
    @pack << @extra.sample
  end

  private

  def find_booster_packs
    @booster_packs = BoosterPack.where(booster_set_id: params[:booster_set_id]).sort
  end
end

app/controllers/booster_sets_controller.rb
class BoosterSetsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @booster_sets = BoosterSet.all
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]

  def show
    @card = Card.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @booster_sets = BoosterSet.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/booster_packs/index.html.erb
<div class="title inner-border">
  <h1><%= @booster_packs.first.booster_set.name %></h1>
</div>

<div class="container">
  <%= link_to "Open a pack", booster_set_booster_pack_path(id: "opened_pack"), class: "button" %>
</div>

<div class="container">
  <div class="booster-cards">
    <% @booster_packs.each do |booster| %>
      <div class="booster-card inner-border style-border">
        <div class="card-number">
          <p><%= booster.card_number %></p>
        </div>
        <div class="card-name">
          <p><%= booster.card.name %></p>
        </div>
        <div class="card-rarity">
          <p><%= booster.card_rarity %></p>
        </div>
        <%= link_to card_path(booster.card_id) do %>
            <img src="<%= booster.card.picture %>" alt="Card Image">
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/booster_packs/show.html.erb
<div class="title inner-border"><h1>Your Pack</h1></div>

<div class="container">
  <div class="text inner-border style-border">
    Each main series Booster Pack is guaranteed a Rare, 7 Commons,
    and a ninth card which will either be another Common or a foil
    card (Super Rare rarity or higher).
  </div>
</div>

<div class="container">
  <a href="#pack" id="pack" class="button">Open another pack</a>
</div>

<div class="container">
  <div class="pack-cards inner-border style-border">
    <% @pack.each do |card| %>
      <div class="pack-card">
        <%= link_to card_path(card) do %>
          <img src="<%= card.card.picture %>" alt="Card Image" class="<%= card.card_rarity %>">
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/booster_sets/index.html.erb
<div class="title inner-border">
  <h1>Booster Sets</h1>
</div>

<div class="container">
  <div class="text inner-border style-border">
    Each main series Booster Pack is guaranteed a Rare, 7 Commons,
    and a ninth card which will either be another Common or a foil
    card (Super Rare rarity or higher).
  </div>
</div>

<div class="container">
  <div class="booster-sets inner-border style-border">
    <% @booster_sets.each do |booster| %>
      <%= link_to booster_set_booster_packs_path(booster) do %>
        <div class="booster-set">
          <img src="<%= booster.picture %>" alt="Booster Set Image">
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/cards/index.html.erb
<p><%= @card.name %></p>
<p><img src="<%= @card.picture %>" alt="Card Image"></p>

app/views/cards/show.html.erb
<div class="container card-frame inner-border style-border">
  <img src="<%= @card.picture %>" alt="Card Image" class="card">
  <div class="card-data style-border">
    <div class="card-name">
      <b>Name:</b> <%= @card.name %>
    </div>
    <div class="card-type">
      <b>Card Type:</b> <%= @card.card %>
    </div>
    <div class="attribute">
      <b>Attribute:</b> <%= @card.monster_attribute %>
    </div>
    <div class="type">
      <b>Type:</b> <%= @card.monster_type %>
    </div>
    <div class="level">
      <b>Level:</b> <%= @card.level %>
    </div>
    <div class="atk">
      <b>Atk:</b> <%= @card.atk %>
    </div>
    <div class="def">
      <b>Def:</b> <%= @card.def %>
    </div>
    <div class="description">
      <b>Description:</b>
      <br><%= @card.description %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Yu-Gi-Oh! Pack Opening Simulator</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
  </head>
  <body>
    <div class="main-container">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <%= yield %>
      <footer class="footer inner-border">This is an unofficial website.</footer>
    </div>

    <%= javascript_pack_tag 'application' %>
    <script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
  </body>
</html>

app/views/pages/home.html.erb
<div class="title inner-border">
  <h1>Yu-Gi-Oh! Pack Opening Simulator</h1>
</div>

<div class="container">
  <%= link_to "Booster Sets", booster_sets_path, class: "button"  %>
</div>

<div class="container carousel style-border">
  <div class="gallery js-flickity"
    data-flickity-options='{ "wrapAround": true }'>
    <% @booster_sets.each do |booster| %>
      <%= link_to booster_set_booster_packs_path(booster) do  %>
        <img class="gallery-cell" src="<%= booster.picture %>" alt="">
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://ms.yugipedia.com//7/79/Chrome_extension_logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


<!--   <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div> -->
</div>